version: "3.8"
services:
  recommendation-redis:
    container_name: recommendation-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: jo0oy/recommendation-redis
    ports:
      - "6379:6379"
  recommendation-database:
    container_name: recommendation-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: jo0oy/recommendation-database
    environment:
      - MARIADB_DATABASE=recommendation
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_ROOT_PASSWORD}
      - MARIADB_USER=${SPRING_DATASOURCE_USERNAME}
      - MARIADB_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  recommendation-app:
    container_name: recommendation-app
    build: .
    depends_on:          # DB, REDIS 컨테이너가 실행된 다음 WEB을 실행시킨다.
      - recommendation-database
      - recommendation-redis
    image: jo0oy/recommendation-app
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
    ports:
      - "80:8080"
    restart: always # depends on은 실행 순서만 컨트롤 할뿐,
      # 컨테이너 안의 서비스가 실행가능한 상태인지까지는 확인 하지 않기 때문에
    # DB 또는 Redis가 아직 실행가능한 상태가 아니여서 실패하는 경우 재시작 하도록 설정
